"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/test/onnx/test_small.onnx
Generated: 2025-12-22 03:36:21

This module was automatically converted from an ONNX model.
"""

__all__ = ["TestTestSmall"]

import torch
import torch.nn as nn


class TestTestSmall(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("c0", torch.empty([2, 1], dtype=torch.float32))
        self.register_buffer("c1", torch.empty([2], dtype=torch.float32))
        self.register_buffer("c2", torch.empty([2, 2], dtype=torch.float32))
        self.register_buffer("c3", torch.empty([2], dtype=torch.float32))
        self.register_buffer("c4", torch.empty([1, 2], dtype=torch.float32))
        self.relu1 = nn.ReLU()
        self.relu2 = nn.ReLU()

    def forward(self, x0):
        x1 = self.c0 @ x0
        x2 = x1 + self.c1
        x3 = self.relu1(x2)
        x4 = self.c2 @ x3
        x5 = x4 + self.c3
        x6 = self.relu2(x5)
        x7 = self.c4 @ x6
        x8 = x7 + 3.5
        return x8
