"""
This file was generated by the torchconverter.
"""

import torch
from torch import Tensor
import torch.nn as nn
from torch.nn import Module


class TinyimagenetResnetMedium(Module):
    def __init__(self):
        super(Module, self).__init__()

        self.Conv_1 = nn.Conv2d(3, 64, (3, 3), stride=(2, 2), padding=(0, 0), dilation=(1, 1), groups=1)
        self.Relu_2 = nn.ReLU()
        self.Conv_3 = nn.Conv2d(64, 128, (1, 1), stride=(2, 2), padding=(0, 0), dilation=(1, 1), groups=1)
        self.Conv_4 = nn.Conv2d(64, 128, (3, 3), stride=(2, 2), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Relu_5 = nn.ReLU()
        self.Conv_6 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Conv_8 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Relu_9 = nn.ReLU()
        self.Conv_10 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Conv_12 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Relu_13 = nn.ReLU()
        self.Conv_14 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Conv_16 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Relu_17 = nn.ReLU()
        self.Conv_18 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Conv_20 = nn.Conv2d(128, 128, (1, 1), stride=(2, 2), padding=(0, 0), dilation=(1, 1), groups=1)
        self.Conv_21 = nn.Conv2d(128, 128, (3, 3), stride=(2, 2), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Relu_22 = nn.ReLU()
        self.Conv_23 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Conv_25 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Relu_26 = nn.ReLU()
        self.Conv_27 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Conv_29 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Relu_30 = nn.ReLU()
        self.Conv_31 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Conv_33 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Relu_34 = nn.ReLU()
        self.Conv_35 = nn.Conv2d(128, 128, (3, 3), stride=(1, 1), padding=(1, 1), dilation=(1, 1), groups=1)
        self.Flatten_37 = nn.Flatten(start_dim=1)
        self.Gemm_38 = nn.Linear(6272, 200, bias=True)
        self.Relu_39 = nn.ReLU()
        self.Gemm_40 = nn.Linear(200, 200, bias=True)

    def forward(self, input_0: Tensor) -> Tensor:

        Conv_1_output_0 = self.Conv_1(input_0)
        Relu_2_output_0 = self.Relu_2(Conv_1_output_0)
        Conv_3_output_0 = self.Conv_3(Relu_2_output_0)
        Conv_4_output_0 = self.Conv_4(Relu_2_output_0)
        Relu_5_output_0 = self.Relu_5(Conv_4_output_0)
        Conv_6_output_0 = self.Conv_6(Relu_5_output_0)
        Add_7_output_0 = Conv_6_output_0 + Conv_3_output_0
        Conv_8_output_0 = self.Conv_8(Add_7_output_0)
        Relu_9_output_0 = self.Relu_9(Conv_8_output_0)
        Conv_10_output_0 = self.Conv_10(Relu_9_output_0)
        Add_11_output_0 = Conv_10_output_0 + Add_7_output_0
        Conv_12_output_0 = self.Conv_12(Add_11_output_0)
        Relu_13_output_0 = self.Relu_13(Conv_12_output_0)
        Conv_14_output_0 = self.Conv_14(Relu_13_output_0)
        Add_15_output_0 = Conv_14_output_0 + Add_11_output_0
        Conv_16_output_0 = self.Conv_16(Add_15_output_0)
        Relu_17_output_0 = self.Relu_17(Conv_16_output_0)
        Conv_18_output_0 = self.Conv_18(Relu_17_output_0)
        Add_19_output_0 = Conv_18_output_0 + Add_15_output_0
        Conv_20_output_0 = self.Conv_20(Add_19_output_0)
        Conv_21_output_0 = self.Conv_21(Add_19_output_0)
        Relu_22_output_0 = self.Relu_22(Conv_21_output_0)
        Conv_23_output_0 = self.Conv_23(Relu_22_output_0)
        Add_24_output_0 = Conv_23_output_0 + Conv_20_output_0
        Conv_25_output_0 = self.Conv_25(Add_24_output_0)
        Relu_26_output_0 = self.Relu_26(Conv_25_output_0)
        Conv_27_output_0 = self.Conv_27(Relu_26_output_0)
        Add_28_output_0 = Conv_27_output_0 + Add_24_output_0
        Conv_29_output_0 = self.Conv_29(Add_28_output_0)
        Relu_30_output_0 = self.Relu_30(Conv_29_output_0)
        Conv_31_output_0 = self.Conv_31(Relu_30_output_0)
        Add_32_output_0 = Conv_31_output_0 + Add_28_output_0
        Conv_33_output_0 = self.Conv_33(Add_32_output_0)
        Relu_34_output_0 = self.Relu_34(Conv_33_output_0)
        Conv_35_output_0 = self.Conv_35(Relu_34_output_0)
        Add_36_output_0 = Conv_35_output_0 + Add_32_output_0
        Flatten_37_output_0 = self.Flatten_37(Add_36_output_0)
        Gemm_38_output_0 = self.Gemm_38(Flatten_37_output_0)
        Relu_39_output_0 = self.Relu_39(Gemm_38_output_0)
        output_41 = self.Gemm_40(Relu_39_output_0)

        return output_41
