"""
This file was generated by the torchconverter.
"""

import torch
from torch import Tensor
import torch.nn as nn
from torch.nn import Module


class TinyimagenetResnetMediumV22Simplified(Module):
    def __init__(self):
        super(Module, self).__init__()

        self.data = torch.load('../nets/TinyImageNet_resnet_medium_v22_simplified.pth')

        self.Conv_1 = nn.Conv2d(3, 64, (3, 3), stride=2)
        self.Conv_1.weight.data = self.data['Initializer_4']
        self.Conv_1.bias.data = self.data['Initializer_5']

        self.Relu_2 = nn.ReLU()
        self.Conv_3 = nn.Conv2d(64, 128, (1, 1), stride=2)
        self.Conv_3.weight.data = self.data['Initializer_10']
        self.Conv_3.bias.data = self.data['Initializer_11']

        self.Conv_4 = nn.Conv2d(64, 128, (3, 3), stride=2, padding=1)
        self.Conv_4.weight.data = self.data['Initializer_6']
        self.Conv_4.bias.data = self.data['Initializer_7']

        self.Relu_5 = nn.ReLU()
        self.Conv_6 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_6.weight.data = self.data['Initializer_8']
        self.Conv_6.bias.data = self.data['Initializer_9']

        self.Conv_8 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_8.weight.data = self.data['Initializer_12']
        self.Conv_8.bias.data = self.data['Initializer_13']

        self.Relu_9 = nn.ReLU()
        self.Conv_10 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_10.weight.data = self.data['Initializer_14']
        self.Conv_10.bias.data = self.data['Initializer_15']

        self.Conv_12 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_12.weight.data = self.data['Initializer_16']
        self.Conv_12.bias.data = self.data['Initializer_17']

        self.Relu_13 = nn.ReLU()
        self.Conv_14 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_14.weight.data = self.data['Initializer_18']
        self.Conv_14.bias.data = self.data['Initializer_19']

        self.Conv_16 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_16.weight.data = self.data['Initializer_20']
        self.Conv_16.bias.data = self.data['Initializer_21']

        self.Relu_17 = nn.ReLU()
        self.Conv_18 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_18.weight.data = self.data['Initializer_22']
        self.Conv_18.bias.data = self.data['Initializer_23']

        self.Conv_20 = nn.Conv2d(128, 128, (1, 1), stride=2)
        self.Conv_20.weight.data = self.data['Initializer_28']
        self.Conv_20.bias.data = self.data['Initializer_29']

        self.Conv_21 = nn.Conv2d(128, 128, (3, 3), stride=2, padding=1)
        self.Conv_21.weight.data = self.data['Initializer_24']
        self.Conv_21.bias.data = self.data['Initializer_25']

        self.Relu_22 = nn.ReLU()
        self.Conv_23 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_23.weight.data = self.data['Initializer_26']
        self.Conv_23.bias.data = self.data['Initializer_27']

        self.Conv_25 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_25.weight.data = self.data['Initializer_30']
        self.Conv_25.bias.data = self.data['Initializer_31']

        self.Relu_26 = nn.ReLU()
        self.Conv_27 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_27.weight.data = self.data['Initializer_32']
        self.Conv_27.bias.data = self.data['Initializer_33']

        self.Conv_29 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_29.weight.data = self.data['Initializer_34']
        self.Conv_29.bias.data = self.data['Initializer_35']

        self.Relu_30 = nn.ReLU()
        self.Conv_31 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_31.weight.data = self.data['Initializer_36']
        self.Conv_31.bias.data = self.data['Initializer_37']

        self.Conv_33 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_33.weight.data = self.data['Initializer_38']
        self.Conv_33.bias.data = self.data['Initializer_39']

        self.Relu_34 = nn.ReLU()
        self.Conv_35 = nn.Conv2d(128, 128, (3, 3), padding=1)
        self.Conv_35.weight.data = self.data['Initializer_40']
        self.Conv_35.bias.data = self.data['Initializer_41']

        self.Flatten_37 = nn.Flatten()
        self.Gemm_38 = nn.Linear(6272, 200)
        self.Gemm_38.weight.data = self.data['Initializer_0']
        self.Gemm_38.bias.data = self.data['Initializer_1']

        self.Relu_39 = nn.ReLU()
        self.Gemm_40 = nn.Linear(200, 200)
        self.Gemm_40.weight.data = self.data['Initializer_2']
        self.Gemm_40.bias.data = self.data['Initializer_3']


    def forward(self, input_0: Tensor) -> Tensor:

        Conv_1_0 = self.Conv_1(input_0)
        Relu_2_0 = self.Relu_2(Conv_1_0)
        Conv_3_0 = self.Conv_3(Relu_2_0)
        Conv_4_0 = self.Conv_4(Relu_2_0)
        Relu_5_0 = self.Relu_5(Conv_4_0)
        Conv_6_0 = self.Conv_6(Relu_5_0)
        Add_7_0 = Conv_6_0 + Conv_3_0
        Conv_8_0 = self.Conv_8(Add_7_0)
        Relu_9_0 = self.Relu_9(Conv_8_0)
        Conv_10_0 = self.Conv_10(Relu_9_0)
        Add_11_0 = Conv_10_0 + Add_7_0
        Conv_12_0 = self.Conv_12(Add_11_0)
        Relu_13_0 = self.Relu_13(Conv_12_0)
        Conv_14_0 = self.Conv_14(Relu_13_0)
        Add_15_0 = Conv_14_0 + Add_11_0
        Conv_16_0 = self.Conv_16(Add_15_0)
        Relu_17_0 = self.Relu_17(Conv_16_0)
        Conv_18_0 = self.Conv_18(Relu_17_0)
        Add_19_0 = Conv_18_0 + Add_15_0
        Conv_20_0 = self.Conv_20(Add_19_0)
        Conv_21_0 = self.Conv_21(Add_19_0)
        Relu_22_0 = self.Relu_22(Conv_21_0)
        Conv_23_0 = self.Conv_23(Relu_22_0)
        Add_24_0 = Conv_23_0 + Conv_20_0
        Conv_25_0 = self.Conv_25(Add_24_0)
        Relu_26_0 = self.Relu_26(Conv_25_0)
        Conv_27_0 = self.Conv_27(Relu_26_0)
        Add_28_0 = Conv_27_0 + Add_24_0
        Conv_29_0 = self.Conv_29(Add_28_0)
        Relu_30_0 = self.Relu_30(Conv_29_0)
        Conv_31_0 = self.Conv_31(Relu_30_0)
        Add_32_0 = Conv_31_0 + Add_28_0
        Conv_33_0 = self.Conv_33(Add_32_0)
        Relu_34_0 = self.Relu_34(Conv_33_0)
        Conv_35_0 = self.Conv_35(Relu_34_0)
        Add_36_0 = Conv_35_0 + Add_32_0
        Flatten_37_0 = self.Flatten_37(Add_36_0)
        Gemm_38_0 = self.Gemm_38(Flatten_37_0)
        Relu_39_0 = self.Relu_39(Gemm_38_0)
        output_41 = self.Gemm_40(Relu_39_0)

        return output_41
