"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/collins_rul_cnn_2023/onnx/NN_rul_small_window_20.onnx
Generated: 2025-12-22 03:36:17

This module was automatically converted from an ONNX model.
"""

__all__ = ["CollinsRulCnn2023NnRulSmallWindow20"]

import torch.nn as nn


class CollinsRulCnn2023NnRulSmallWindow20(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv2d1 = nn.Conv2d(1, 5, (5, 1))
        self.relu1 = nn.ReLU()
        self.conv2d2 = nn.Conv2d(5, 10, (5, 1))
        self.relu2 = nn.ReLU()
        self.conv2d3 = nn.Conv2d(10, 5, (5, 1))
        self.relu3 = nn.ReLU()
        self.conv2d4 = nn.Conv2d(5, 5, (3, 1))
        self.relu4 = nn.ReLU()
        self.conv2d5 = nn.Conv2d(5, 100, (6, 20))
        self.relu5 = nn.ReLU()
        self.dropout1 = nn.Dropout(0.5)
        self.conv2d6 = nn.Conv2d(100, 1, 1)
        self.flatten1 = nn.Flatten(1)

    def forward(self, x0):
        x1 = self.conv2d1(x0)
        x2 = self.relu1(x1)
        x3 = self.conv2d2(x2)
        x4 = self.relu2(x3)
        x5 = self.conv2d3(x4)
        x6 = self.relu3(x5)
        x7 = self.conv2d4(x6)
        x8 = self.relu4(x7)
        x9 = self.conv2d5(x8)
        x10 = self.relu5(x9)
        x11 = self.dropout1(x10)
        x12 = self.conv2d6(x11)
        x13 = self.flatten1(x12)
        return x13
