"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/linearizenn/onnx/AllInOne_80_30.onnx
Generated: 2025-12-22 03:36:17

This module was automatically converted from an ONNX model.
"""

__all__ = ["LinearizennAllinone8030"]

import torch
import torch.nn as nn


class LinearizennAllinone8030(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("c0", torch.empty([2, 1], dtype=torch.float32))
        self.register_buffer("c5", torch.empty([2, 1], dtype=torch.float32))
        self.register_buffer("c6", torch.empty([2, 2], dtype=torch.float32))
        self.linear1 = nn.Linear(4, 256)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(256, 256)
        self.relu2 = nn.ReLU()
        self.linear3 = nn.Linear(256, 256)
        self.relu3 = nn.ReLU()
        self.linear4 = nn.Linear(256, 256)
        self.relu4 = nn.ReLU()
        self.linear5 = nn.Linear(256, 16)
        self.relu5 = nn.ReLU()
        self.linear6 = nn.Linear(16, 8)
        self.relu6 = nn.ReLU()
        self.linear7 = nn.Linear(8, 8)
        self.relu7 = nn.ReLU()
        self.linear8 = nn.Linear(8, 2)

    def forward(self, x0):
        x1 = self.linear1(x0)
        x2 = self.relu1(x1)
        x3 = self.linear2(x2)
        x4 = self.relu2(x3)
        x5 = self.linear3(x4)
        x6 = self.relu3(x5)
        x7 = self.linear4(x6)
        x8 = self.relu4(x7)
        x9 = self.linear5(x8)
        x10 = self.relu5(x9)
        x11 = self.linear6(x10)
        x12 = self.relu6(x11)
        x13 = self.linear7(x12)
        x14 = self.relu7(x13)
        x15 = self.linear8(x14)
        x16 = x15 @ self.c0
        x17 = x0[:, 2:]
        x18 = x17 @ self.c5
        x19 = torch.cat([x16, x18], dim=1)
        x20 = x19 @ self.c6
        return x20
