"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/cora/onnx/cifar10-set.onnx
Generated: 2025-12-22 03:36:17

This module was automatically converted from an ONNX model.
"""

__all__ = ["CoraCifar10Set"]

import torch
import torch.nn as nn


class CoraCifar10Set(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("c2", torch.empty([3072, 250], dtype=torch.float32))
        self.register_buffer("c3", torch.empty([250], dtype=torch.float32))
        self.register_buffer("c4", torch.empty([250, 250], dtype=torch.float32))
        self.register_buffer("c5", torch.empty([250], dtype=torch.float32))
        self.register_buffer("c6", torch.empty([250, 250], dtype=torch.float32))
        self.register_buffer("c7", torch.empty([250], dtype=torch.float32))
        self.register_buffer("c8", torch.empty([250, 250], dtype=torch.float32))
        self.register_buffer("c9", torch.empty([250], dtype=torch.float32))
        self.register_buffer("c10", torch.empty([250, 250], dtype=torch.float32))
        self.register_buffer("c11", torch.empty([250], dtype=torch.float32))
        self.register_buffer("c12", torch.empty([250, 250], dtype=torch.float32))
        self.register_buffer("c13", torch.empty([250], dtype=torch.float32))
        self.register_buffer("c14", torch.empty([250, 250], dtype=torch.float32))
        self.register_buffer("c15", torch.empty([250], dtype=torch.float32))
        self.register_buffer("c16", torch.empty([250, 10], dtype=torch.float32))
        self.register_buffer("c17", torch.empty([10], dtype=torch.float32))
        self.relu1 = nn.ReLU()
        self.relu2 = nn.ReLU()
        self.relu3 = nn.ReLU()
        self.relu4 = nn.ReLU()
        self.relu5 = nn.ReLU()
        self.relu6 = nn.ReLU()
        self.relu7 = nn.ReLU()

    def forward(self, x0):
        x1 = x0 * 3.974562883377075
        x2 = x1 + -1.8815580606460571
        x3 = x2 @ self.c2
        x4 = x3 + self.c3
        x5 = self.relu1(x4)
        x6 = x5 @ self.c4
        x7 = x6 + self.c5
        x8 = self.relu2(x7)
        x9 = x8 @ self.c6
        x10 = x9 + self.c7
        x11 = self.relu3(x10)
        x12 = x11 @ self.c8
        x13 = x12 + self.c9
        x14 = self.relu4(x13)
        x15 = x14 @ self.c10
        x16 = x15 + self.c11
        x17 = self.relu5(x16)
        x18 = x17 @ self.c12
        x19 = x18 + self.c13
        x20 = self.relu6(x19)
        x21 = x20 @ self.c14
        x22 = x21 + self.c15
        x23 = self.relu7(x22)
        x24 = x23 @ self.c16
        x25 = x24 + self.c17
        return x25
