"""Add file headers and decorations to generated PyTorch code."""

__docformat__ = "restructuredtext"
__all__ = ["add_file_header"]

from pathlib import Path


def add_file_header(
    code: str,
    class_name: str,
    source_onnx: str = "",
) -> str:
    """Add file header with metadata and ``__all__`` to generated code.

    The header is deterministic: identical ONNX -> identical output bytes.
    Earlier versions baked ``datetime.now()`` and the absolute ``source_onnx``
    path into every emitted file, which broke bit-reproducibility and
    content-hash caching even though every other stage was pure. The
    timestamp added zero recoverable information (git history records the
    conversion commit) and the absolute path leaked the converter's
    machine into every artifact; we keep just the source filename so a
    reader still knows which ONNX the module came from.

    :param code: Generated PyTorch code.
    :param class_name: Name of the generated class.
    :param source_onnx: Path to source ONNX file (only the filename is kept).

    :return: Code with header prepended.
    """
    source_name = Path(source_onnx).name if source_onnx else ""

    header = f'''"""PyTorch module generated by TorchONNX.

Source: {source_name}

This module was automatically converted from an ONNX model.
"""

__all__ = ["{class_name}"]

'''
    return header + code
