"""Add file headers and decorations to generated PyTorch code."""

__docformat__ = "restructuredtext"
__all__ = ["add_file_header"]

from datetime import datetime


def add_file_header(
    code: str,
    class_name: str,
    source_onnx: str = "",
) -> str:
    """Add file header with copyright, metadata, and __all__ to generated code.

    :param code: Generated PyTorch code
    :param class_name: Name of the generated class
    :param source_onnx: Path to source ONNX file
    :return: Code with header prepended
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    header = f'''"""PyTorch module generated by TorchONNX.

Source: {source_onnx}
Generated: {timestamp}

This module was automatically converted from an ONNX model.
"""

__all__ = ["{class_name}"]

'''
    return header + code
