__docformat__ = "restructuredtext"
__all__ = ["gen_header_code"]

import onnx


def _gen_imports() -> str:
    s = (
        '"""\n'
        "This file was generated by the torchconverter.\n"
        '"""\n\n'
        "import torch\n"
        "from torch import Tensor\n"
        "import torch.nn as nn\n"
        "from torch.nn import Module\n"
        # "from torch.nn import functional as F\n"
        "\n\n"
    )
    return s


def _gen_class_header(model_name: str) -> str:
    s = f"class {model_name}(Module):\n"
    return s


def gen_header_code(model: onnx.ModelProto, model_name: str) -> str:
    content = _gen_imports()
    content += _gen_class_header(model_name)

    return content
