__docformat__ = "restructuredtext"
__all__ = ["gen_header_code"]

import onnx


def _gen_imports() -> str:
    content = (
        '"""\n'
        "This file was generated by the torchconverter.\n"
        '"""\n\n'
        "import torch\n"
        "from torch import Tensor\n"
        "import torch.nn as nn\n"
        "from torch.nn import Module\n"
        # "from torch.nn import functional as F\n"
        "\n\n"
    )
    return content


def _get_input_output_shape(node: onnx.ValueInfoProto):
    shape = []
    for dim in node.type.tensor_type.shape.dim:
        if dim.dim_param:
            shape.append(dim.dim_param)
        else:
            shape.append(dim.dim_value)
    return shape


def _gen_model_info(model: onnx.ModelProto) -> str:
    content = f"# Model name: {model.graph.name}\n"

    for input_node in model.graph.input:
        content += f"# Input name: {input_node.name}\n"
        shape = _get_input_output_shape(input_node)
        content += f"# Input shape: {shape}\n"

    for output_node in model.graph.output:
        content += f"# Output name: {output_node.name}\n"
        shape = _get_input_output_shape(output_node)
        content += f"# Output shape: {shape}\n"

    content += "\n"

    return content


def _gen_class_header(model_name: str) -> str:
    return f"class {model_name}(Module):\n"


def gen_header_code(model: onnx.ModelProto, model_name: str) -> str:
    content = _gen_imports()
    content += _gen_model_info(model)
    content += _gen_class_header(model_name)

    return content
