"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/metaroom_2023/onnx/4cnn_tz_19_3_no_custom_OP.onnx
Generated: 2025-12-22 03:36:17

This module was automatically converted from an ONNX model.
"""

__all__ = ["Metaroom20234cnnTz193NoCustomOp"]

import torch.nn as nn


class Metaroom20234cnnTz193NoCustomOp(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv2d1 = nn.Conv2d(3, 8, 4, stride=2, padding=1)
        self.relu1 = nn.ReLU()
        self.conv2d2 = nn.Conv2d(8, 16, 4, stride=2, padding=1)
        self.relu2 = nn.ReLU()
        self.linear1 = nn.Linear(1792, 256)
        self.relu3 = nn.ReLU()
        self.linear2 = nn.Linear(256, 20)

    def forward(self, x0):
        x1 = self.conv2d1(x0)
        x2 = self.relu1(x1)
        x3 = self.conv2d2(x2)
        x4 = self.relu2(x3)
        x5 = x4.flatten(1)
        x6 = self.linear1(x5)
        x7 = self.relu3(x6)
        x8 = self.linear2(x7)
        return x8
