"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/metaroom_2023/onnx/6cnn_tz_52_8_no_custom_OP.onnx
Generated: 2025-12-22 03:36:18

This module was automatically converted from an ONNX model.
"""

__all__ = ["Metaroom20236cnnTz528NoCustomOp"]

import torch.nn as nn


class Metaroom20236cnnTz528NoCustomOp(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv2d1 = nn.Conv2d(3, 32, 3, padding=1)
        self.relu1 = nn.ReLU()
        self.conv2d2 = nn.Conv2d(32, 32, 3, padding=1)
        self.relu2 = nn.ReLU()
        self.conv2d3 = nn.Conv2d(32, 64, 3, stride=2, padding=1)
        self.relu3 = nn.ReLU()
        self.conv2d4 = nn.Conv2d(64, 64, 3, padding=1)
        self.relu4 = nn.ReLU()
        self.linear1 = nn.Linear(28672, 256)
        self.relu5 = nn.ReLU()
        self.linear2 = nn.Linear(256, 20)

    def forward(self, x0):
        x1 = self.conv2d1(x0)
        x2 = self.relu1(x1)
        x3 = self.conv2d2(x2)
        x4 = self.relu2(x3)
        x5 = self.conv2d3(x4)
        x6 = self.relu3(x5)
        x7 = self.conv2d4(x6)
        x8 = self.relu4(x7)
        x9 = x8.flatten(1)
        x10 = self.linear1(x9)
        x11 = self.relu5(x10)
        x12 = self.linear2(x11)
        return x12
