"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/dist_shift_2023/onnx/mnist_concat.onnx
Generated: 2025-12-22 03:36:17

This module was automatically converted from an ONNX model.
"""

__all__ = ["DistShift2023MnistConcat"]

import torch.nn as nn


class DistShift2023MnistConcat(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(792, 200)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(200, 784)
        self.sigmoid1 = nn.Sigmoid()
        self.linear3 = nn.Linear(784, 32)
        self.relu2 = nn.ReLU()
        self.linear4 = nn.Linear(32, 32)
        self.relu3 = nn.ReLU()
        self.linear5 = nn.Linear(32, 10)

    def forward(self, x0):
        x1 = self.linear1(x0)
        x2 = self.relu1(x1)
        x3 = self.linear2(x2)
        x4 = self.sigmoid1(x3)
        x5 = x4.reshape(-1, 1, 28, 28)
        x6 = x5.reshape(-1, 784)
        x7 = self.linear3(x6)
        x8 = self.relu2(x7)
        x9 = self.linear4(x8)
        x10 = self.relu3(x9)
        x11 = self.linear5(x10)
        return x11
