"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/nn4sys_2023/onnx/lindex.onnx
Generated: 2025-12-22 03:36:18

This module was automatically converted from an ONNX model.
"""

__all__ = ["Nn4sys2023Lindex"]

import torch.nn as nn


class Nn4sys2023Lindex(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(1, 128)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(128, 128)
        self.relu2 = nn.ReLU()
        self.linear3 = nn.Linear(128, 128)
        self.relu3 = nn.ReLU()
        self.linear4 = nn.Linear(128, 1)

    def forward(self, x0):
        x1 = self.linear1(x0)
        x2 = self.relu1(x1)
        x3 = self.linear2(x2)
        x4 = self.relu2(x3)
        x5 = self.linear3(x4)
        x6 = self.relu3(x5)
        x7 = self.linear4(x6)
        return x7
