"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/nn4sys_2023/onnx/pensieve_big_parallel.onnx
Generated: 2025-12-22 03:36:21

This module was automatically converted from an ONNX model.
"""

__all__ = ["Nn4sys2023PensieveBigParallel"]

import torch
import torch.nn as nn


class Nn4sys2023PensieveBigParallel(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("c28", torch.empty([1], dtype=torch.int64))
        self.register_buffer("c29", torch.empty([6, 1], dtype=torch.float32))
        self.register_buffer("c55", torch.empty([1], dtype=torch.int64))
        self.linear1 = nn.Linear(1, 128)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(1, 128)
        self.relu2 = nn.ReLU()
        self.conv1d1 = nn.Conv1d(1, 128, 4)
        self.relu3 = nn.ReLU()
        self.conv1d2 = nn.Conv1d(1, 128, 4)
        self.relu4 = nn.ReLU()
        self.conv1d3 = nn.Conv1d(1, 128, 4)
        self.relu5 = nn.ReLU()
        self.linear3 = nn.Linear(1, 128)
        self.flatten1 = nn.Flatten(1)
        self.flatten2 = nn.Flatten(1)
        self.flatten3 = nn.Flatten(1)
        self.linear4 = nn.Linear(2048, 256)
        self.relu6 = nn.ReLU()
        self.linear5 = nn.Linear(256, 6)
        self.relu7 = nn.ReLU()
        self.linear6 = nn.Linear(1, 128)
        self.relu8 = nn.ReLU()
        self.linear7 = nn.Linear(1, 128)
        self.relu9 = nn.ReLU()
        self.conv1d4 = nn.Conv1d(1, 128, 4)
        self.relu10 = nn.ReLU()
        self.conv1d5 = nn.Conv1d(1, 128, 4)
        self.relu11 = nn.ReLU()
        self.conv1d6 = nn.Conv1d(1, 128, 4)
        self.relu12 = nn.ReLU()
        self.linear8 = nn.Linear(1, 128)
        self.flatten4 = nn.Flatten(1)
        self.flatten5 = nn.Flatten(1)
        self.flatten6 = nn.Flatten(1)
        self.linear9 = nn.Linear(2048, 256)
        self.relu13 = nn.ReLU()
        self.linear10 = nn.Linear(256, 6)
        self.relu14 = nn.ReLU()

    def forward(self, x0):
        x1 = x0.reshape(-1, 12, 8)
        x2, x3 = x1.split([6, 6], dim=1)
        x4 = x2[:, 0:1]
        x5 = x4[:, :, -1]
        x6 = self.linear1(x5)
        x7 = self.relu1(x6)
        x8 = x2[:, 1:2]
        x9 = x8[:, :, -1]
        x10 = self.linear2(x9)
        x11 = self.relu2(x10)
        x12 = x2[:, 2:3]
        x13 = self.conv1d1(x12)
        x14 = self.relu3(x13)
        x15 = x2[:, 3:4]
        x16 = self.conv1d2(x15)
        x17 = self.relu4(x16)
        x18 = x2[:, 4:5]
        x19 = x18[:, :, 0:6]
        x20 = self.conv1d3(x19)
        x21 = self.relu5(x20)
        x22 = x18[:, :, -1]
        x23 = self.linear3(x22)
        x24 = self.flatten1(x14)
        x25 = self.flatten2(x17)
        x26 = self.flatten3(x21)
        x27 = torch.cat([x7, x11, x24, x25, x26, x23], dim=1)
        x28 = self.linear4(x27)
        x29 = self.relu6(x28)
        x30 = self.linear5(x29)
        x31 = self.relu7(x30)
        x32 = x31**3
        x33 = torch.sum(x32, self.c28.tolist(), keepdim=True)
        x34 = x32 / x33
        x35 = x34 @ self.c29
        x36 = x3[:, 0:1]
        x37 = x36[:, :, -1]
        x38 = self.linear6(x37)
        x39 = self.relu8(x38)
        x40 = x3[:, 1:2]
        x41 = x40[:, :, -1]
        x42 = self.linear7(x41)
        x43 = self.relu9(x42)
        x44 = x3[:, 2:3]
        x45 = self.conv1d4(x44)
        x46 = self.relu10(x45)
        x47 = x3[:, 3:4]
        x48 = self.conv1d5(x47)
        x49 = self.relu11(x48)
        x50 = x3[:, 4:5]
        x51 = x50[:, :, 0:6]
        x52 = self.conv1d6(x51)
        x53 = self.relu12(x52)
        x54 = x50[:, :, -1]
        x55 = self.linear8(x54)
        x56 = self.flatten4(x46)
        x57 = self.flatten5(x49)
        x58 = self.flatten6(x53)
        x59 = torch.cat([x39, x43, x56, x57, x58, x55], dim=1)
        x60 = self.linear9(x59)
        x61 = self.relu13(x60)
        x62 = self.linear10(x61)
        x63 = self.relu14(x62)
        x64 = x63**3
        x65 = torch.sum(x64, self.c55.tolist(), keepdim=True)
        x66 = x64 / x65
        x67 = x66 @ self.c29
        x68 = x35 - x67
        return x68
