"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/nn4sys_2023/onnx/pensieve_big_simple.onnx
Generated: 2025-12-22 03:36:21

This module was automatically converted from an ONNX model.
"""

__all__ = ["Nn4sys2023PensieveBigSimple"]

import torch
import torch.nn as nn


class Nn4sys2023PensieveBigSimple(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(1, 128)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(1, 128)
        self.relu2 = nn.ReLU()
        self.conv1d1 = nn.Conv1d(1, 128, 4)
        self.relu3 = nn.ReLU()
        self.conv1d2 = nn.Conv1d(1, 128, 4)
        self.relu4 = nn.ReLU()
        self.conv1d3 = nn.Conv1d(1, 128, 4)
        self.relu5 = nn.ReLU()
        self.linear3 = nn.Linear(1, 128)
        self.linear4 = nn.Linear(2048, 256)
        self.relu6 = nn.ReLU()
        self.linear5 = nn.Linear(256, 6)

    def forward(self, x0):
        x1 = x0.reshape(-1, 6, 8)
        x2 = x1[:, 0:1]
        x3 = x2[:, :, -1]
        x4 = self.linear1(x3)
        x5 = self.relu1(x4)
        x6 = x1[:, 1:2]
        x7 = x6[:, :, -1]
        x8 = self.linear2(x7)
        x9 = self.relu2(x8)
        x10 = x1[:, 2:3]
        x11 = self.conv1d1(x10)
        x12 = self.relu3(x11)
        x13 = x1[:, 3:4]
        x14 = self.conv1d2(x13)
        x15 = self.relu4(x14)
        x16 = x1[:, 4:5]
        x17 = x16[:, :, 0:6]
        x18 = self.conv1d3(x17)
        x19 = self.relu5(x18)
        x20 = x16[:, :, -1]
        x21 = self.linear3(x20)
        x22 = x12.flatten(1)
        x23 = x15.flatten(1)
        x24 = x19.flatten(1)
        x25 = torch.cat([x5, x9, x22, x23, x24, x21], dim=1)
        x26 = self.linear4(x25)
        x27 = self.relu6(x26)
        x28 = self.linear5(x27)
        return x28
