"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/traffic_signs_recognition_2023/onnx/3_30_30_QConv_16_3_QConv_32_2_Dense_43_ep_30.onnx
Generated: 2025-12-22 03:36:23

This module was automatically converted from an ONNX model.
"""

__all__ = ["TrafficSignsRecognition202333030Qconv163Qconv322Dense43Ep30"]

import torch
import torch.nn as nn


class TrafficSignsRecognition202333030Qconv163Qconv322Dense43Ep30(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("c2", torch.empty([23328, 43], dtype=torch.float32))
        self.conv2d1 = nn.Conv2d(3, 16, 3, bias=False)
        self.conv2d2 = nn.Conv2d(16, 32, 2, bias=False)
        self.softmax1 = nn.Softmax(-1)

    def forward(self, x0):
        x1 = x0.permute((0, 3, 1, 2))
        x2 = self.conv2d1(x1)
        x3 = x2.permute((0, 2, 3, 1))
        x4 = x3.sign()
        x5 = x4 + 0.10000000149011612
        x6 = x5.sign()
        x7 = x6.permute((0, 3, 1, 2))
        x8 = self.conv2d2(x7)
        x9 = x8.permute((0, 2, 3, 1))
        x10 = x9.reshape(-1, 23328)
        x11 = x10.sign()
        x12 = x11 + 0.10000000149011612
        x13 = x12.sign()
        x14 = x13 @ self.c2
        x15 = self.softmax1(x14)
        return x15
