"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/traffic_signs_recognition_2023/onnx/3_48_48_QConv_32_5_MP_2_BN_QConv_64_5_MP_2_BN_QConv_64_3_BN_Dense_256_BN_Dense_43_ep_30.onnx
Generated: 2025-12-22 03:36:23

This module was automatically converted from an ONNX model.
"""

__all__ = [
    "TrafficSignsRecognition202334848Qconv325Mp2BnQconv645Mp2BnQconv643BnDense256BnDense43Ep30"
]

import torch
import torch.nn as nn


class TrafficSignsRecognition202334848Qconv325Mp2BnQconv645Mp2BnQconv643BnDense256BnDense43Ep30(
    nn.Module
):
    def __init__(self):
        super().__init__()
        self.register_buffer("c2", torch.empty([3136, 256], dtype=torch.float32))
        self.register_buffer("c3", torch.empty([256], dtype=torch.float32))
        self.register_buffer("c4", torch.empty([256], dtype=torch.float32))
        self.register_buffer("c5", torch.empty([256, 43], dtype=torch.float32))
        self.conv2d1 = nn.Conv2d(3, 32, 5, bias=False)
        self.maxpool2d1 = nn.MaxPool2d((2, 2), stride=2)
        self.batchnorm2d1 = nn.BatchNorm2d(
            32,
            eps=0.0010000000474974513,
            momentum=0.09999999999999998,
        )
        self.conv2d2 = nn.Conv2d(32, 64, 5, bias=False)
        self.maxpool2d2 = nn.MaxPool2d((2, 2), stride=2)
        self.batchnorm2d2 = nn.BatchNorm2d(
            64,
            eps=0.0010000000474974513,
            momentum=0.09999999999999998,
        )
        self.conv2d3 = nn.Conv2d(64, 64, 3)
        self.softmax1 = nn.Softmax(-1)

    def forward(self, x0):
        x1 = x0.permute((0, 3, 1, 2))
        x2 = self.conv2d1(x1)
        x3 = self.maxpool2d1(x2)
        x4 = self.batchnorm2d1(x3)
        x5 = x4.permute((0, 2, 3, 1))
        x6 = x5.sign()
        x7 = x6 + 0.10000000149011612
        x8 = x7.sign()
        x9 = x8.permute((0, 3, 1, 2))
        x10 = self.conv2d2(x9)
        x11 = self.maxpool2d2(x10)
        x12 = self.batchnorm2d2(x11)
        x13 = x12.permute((0, 2, 3, 1))
        x14 = x13.sign()
        x15 = x14 + 0.10000000149011612
        x16 = x15.sign()
        x17 = x16.permute((0, 3, 1, 2))
        x18 = self.conv2d3(x17)
        x19 = x18.permute((0, 2, 3, 1))
        x20 = x19.reshape(-1, 3136)
        x21 = x20.sign()
        x22 = x21 + 0.10000000149011612
        x23 = x22.sign()
        x24 = x23 @ self.c2
        x25 = x24 * self.c3
        x26 = x25 + self.c4
        x27 = x26.sign()
        x28 = x27 + 0.10000000149011612
        x29 = x28.sign()
        x30 = x29 @ self.c5
        x31 = self.softmax1(x30)
        return x31
