"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/safenlp/onnx/ruarobot_perturbations_0.onnx
Generated: 2025-12-22 03:36:21

This module was automatically converted from an ONNX model.
"""

__all__ = ["SafenlpRuarobotPerturbations0"]

import torch
import torch.nn as nn


class SafenlpRuarobotPerturbations0(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("c0", torch.empty([30, 128], dtype=torch.float32))
        self.register_buffer("c1", torch.empty([128], dtype=torch.float32))
        self.register_buffer("c2", torch.empty([128, 2], dtype=torch.float32))
        self.register_buffer("c3", torch.empty([2], dtype=torch.float32))
        self.relu1 = nn.ReLU()

    def forward(self, x0):
        x1 = x0 @ self.c0
        x2 = x1 + self.c1
        x3 = self.relu1(x2)
        x4 = x3 @ self.c2
        x5 = x4 + self.c3
        return x5
