"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/lsnc/onnx/quadrotor2d_state.onnx
Generated: 2025-12-22 03:36:17

This module was automatically converted from an ONNX model.
"""

__all__ = ["LsncQuadrotor2dState"]

import torch
import torch.nn as nn


class LsncQuadrotor2dState(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("c0", torch.empty([6], dtype=torch.float32))
        self.register_buffer("c1", torch.empty([6, 8], dtype=torch.float32))
        self.register_buffer("c2", torch.empty([8], dtype=torch.float32))
        self.register_buffer("c3", torch.empty([8, 2], dtype=torch.float32))
        self.register_buffer("c4", torch.empty([2], dtype=torch.float32))
        self.register_buffer("c5", torch.empty([2], dtype=torch.float32))
        self.register_buffer("c6", torch.empty([2], dtype=torch.float32))
        self.register_buffer("c7", torch.empty([2], dtype=torch.float32))
        self.register_buffer("c8", torch.empty([2], dtype=torch.float32))
        self.register_buffer("c9", torch.empty([2], dtype=torch.float32))
        self.register_buffer("c37", torch.empty([6], dtype=torch.float32))
        self.register_buffer("c38", torch.empty([6, 6], dtype=torch.float32))
        self.register_buffer("c39", torch.empty([6, 6], dtype=torch.float32))
        self.register_buffer("c40", torch.empty([6, 6], dtype=torch.float32))
        self.register_buffer("c41", torch.empty([1], dtype=torch.int64))
        self.register_buffer("c43", torch.empty([1], dtype=torch.int64))
        self.register_buffer("c44", torch.empty([6], dtype=torch.float32))
        self.register_buffer("c46", torch.empty([6], dtype=torch.float32))
        self.linear1 = nn.Linear(6, 8)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(8, 2)
        self.relu2 = nn.ReLU()
        self.relu3 = nn.ReLU()
        self.relu4 = nn.ReLU()

    def forward(self, x0):
        x1 = self.linear1(x0)
        x2 = self.relu1(x1)
        x3 = self.linear2(x2)
        x4 = self.c0 @ self.c1
        x5 = self.c2 + x4
        x6 = self.relu2(x5)
        x7 = x6 @ self.c3
        x8 = self.c4 + x7
        x9 = x3 - x8
        x10 = x9 + self.c5
        x11 = x10 - self.c6
        x12 = self.relu3(x11)
        x13 = x12 + self.c7
        x14 = self.c8 - x13
        x15 = self.relu4(x14)
        x16 = x15 - self.c9
        x17 = -x16
        x18 = x0[:, 0:3]
        x19 = x18[:, 2:]
        x20 = x19.sin()
        x21 = x17[:, 0:1]
        x22 = x17[:, 1:]
        x23 = x21 + x22
        x24 = x20 * x23
        x25 = x24 * -2.0576131343841553
        x26 = x19.cos()
        x27 = x26 * x23
        x28 = x27 * 2.0576131343841553
        x29 = x28 - 9.8100004196167
        x30 = x21 - x22
        x31 = x30 * 65.27415466308594
        x32 = torch.cat([x25, x29, x31], dim=1)
        x33 = x0[:, 3:]
        x34 = x32 * 0.009999999776482582
        x35 = x33 + x34
        x36 = x35 + x33
        x37 = x36 / 2
        x38 = x37 * 0.009999999776482582
        x39 = x18 + x38
        x40 = torch.cat([x39, x35], dim=1)
        x41 = x0 - self.c37
        x42 = self.c38 @ self.c39
        x43 = self.c40 + x42
        x44 = x41 @ x43
        x45 = x41 * x44
        x46 = torch.sum(x45, self.c41.tolist(), keepdim=True)
        x47 = x0 * 1
        x48 = x40 - x47
        x49 = x40 + x47
        x50 = x49 @ x43
        x51 = x48 * x50
        x52 = torch.sum(x51, self.c43.tolist(), keepdim=True)
        x53 = self.c44 @ x43
        x54 = x48 * x53
        x55 = torch.sum(x54, self.c43.tolist(), keepdim=True)
        x56 = x55 * 2
        x57 = x52 - x56
        x58 = self.c46 * x53
        x59 = torch.sum(x58, self.c43.tolist(), keepdim=True)
        x60 = x59 * 0
        x61 = x57 + x60
        x62 = -x61
        x63 = torch.cat([x62, x46, x40], dim=1)
        return x63
