"""PyTorch module generated by TorchONNX.

Source: /mnt/hdd1/zhongkui/rover_project/rover_alpha/torchonnx/tests/vnncomp2024_benchmarks/ml4acopf_2024/onnx/300_ieee_ml4acopf-linear-residual.onnx
Generated: 2025-12-22 03:36:18

This module was automatically converted from an ONNX model.
"""

__all__ = ["Ml4acopf2024300IeeeMl4acopfLinearResidual"]

import torch
import torch.nn as nn


class Ml4acopf2024300IeeeMl4acopfLinearResidual(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("c5", torch.empty([54], dtype=torch.float32))
        self.register_buffer("c6", torch.empty([54], dtype=torch.float32))
        self.register_buffer("c8", torch.empty([438], dtype=torch.float32))
        self.register_buffer("c9", torch.empty([438], dtype=torch.float32))
        self.register_buffer("c38", torch.empty([411], dtype=torch.int64))
        self.register_buffer("c39", torch.empty([411], dtype=torch.int64))
        self.register_buffer("c53", torch.empty([18], dtype=torch.float32))
        self.register_buffer("c54", torch.empty([18], dtype=torch.float32))
        self.register_buffer("c68", torch.empty([18], dtype=torch.float32))
        self.register_buffer("c69", torch.empty([18], dtype=torch.float32))
        self.register_buffer("c72", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c73", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c74", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c75", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c76", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c77", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c78", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c79", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c80", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c81", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c82", torch.empty([411], dtype=torch.float32))
        self.register_buffer("c83", torch.empty([300, 201], dtype=torch.float32))
        self.register_buffer("c84", torch.empty([300, 69], dtype=torch.float32))
        self.register_buffer("c85", torch.empty([300, 411], dtype=torch.float32))
        self.register_buffer("c86", torch.empty([300, 411], dtype=torch.float32))
        self.register_buffer("c87", torch.empty([300], dtype=torch.float32))
        self.register_buffer("c88", torch.empty([300], dtype=torch.float32))
        self.linear1 = nn.Linear(402, 256)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(256, 256)
        self.relu2 = nn.ReLU()
        self.linear3 = nn.Linear(256, 512)
        self.relu3 = nn.ReLU()
        self.linear4 = nn.Linear(512, 738)
        self.relu4 = nn.ReLU()
        self.relu5 = nn.ReLU()
        self.relu6 = nn.ReLU()
        self.relu7 = nn.ReLU()
        self.relu8 = nn.ReLU()
        self.relu9 = nn.ReLU()
        self.relu10 = nn.ReLU()
        self.relu11 = nn.ReLU()
        self.relu12 = nn.ReLU()

    def forward(self, x0):
        x1 = self.linear1(x0)
        x2 = self.relu1(x1)
        x3 = self.linear2(x2)
        x4 = self.relu2(x3)
        x5 = self.linear3(x4)
        x6 = self.relu3(x5)
        x7 = self.linear4(x6)
        x8 = x7[:, 0:438]
        x9 = x8.unsqueeze(-1)
        x10 = x9 - self.c5
        x11 = self.relu4(x10)
        x12 = x11 @ self.c6
        x13 = x12 + 4.539787187241018e-05
        x14 = x13 * self.c8
        x15 = x14 + self.c9
        x16 = x7[:, 438:]
        x17 = torch.cat([x15, x16], dim=1)
        x18 = x0[:, 0:201]
        x19 = x0[:, 201:402]
        x20 = x17[:, 0:69]
        x21 = x17[:, 69:138]
        x22 = x17[:, 138:438]
        x23 = x17[:, 438:738]
        x24 = x23.index_select(1, self.c38.reshape(-1).long())
        x25 = x23.index_select(1, self.c39.reshape(-1).long())
        x26 = x24 - x25
        x27 = x22.index_select(1, self.c38.reshape(-1).long())
        x28 = x22.index_select(1, self.c39.reshape(-1).long())
        x29 = x27 * x27
        x30 = x28 * x28
        x31 = x26 + 1.5707963705062866
        x32 = x31 / 6.2831854820251465
        x33 = x32.floor()
        x34 = x33 * 6.2831854820251465
        x35 = x31 - x34
        x36 = x35 - 1.5707963705062866
        x37 = x36 * -1
        x38 = self.relu5(x36)
        x39 = x38 * 2
        x40 = x37 + x39
        x41 = 3.1415927410125732 - x40
        x42 = x41 * -1
        x43 = self.relu6(x41)
        x44 = x43 * 2
        x45 = x42 + x44
        x46 = x45 - 1.5707963705062866
        x47 = x46 * -1
        x48 = self.relu7(x46)
        x49 = x48 * 2
        x50 = x47 + x49
        x51 = x50.unsqueeze(-1)
        x52 = x51 - self.c53
        x53 = self.relu8(x52)
        x54 = x53 @ self.c54
        x55 = x54 + 1
        x56 = x46 * x55
        x57 = x26 / 6.2831854820251465
        x58 = x57.floor()
        x59 = x58 * 6.2831854820251465
        x60 = x26 - x59
        x61 = x60 - 1.5707963705062866
        x62 = x61 * -1
        x63 = self.relu9(x61)
        x64 = x63 * 2
        x65 = x62 + x64
        x66 = 3.1415927410125732 - x65
        x67 = x66 * -1
        x68 = self.relu10(x66)
        x69 = x68 * 2
        x70 = x67 + x69
        x71 = x70 - 1.5707963705062866
        x72 = x71 * -1
        x73 = self.relu11(x71)
        x74 = x73 * 2
        x75 = x72 + x74
        x76 = x75.unsqueeze(-1)
        x77 = x76 - self.c68
        x78 = self.relu12(x77)
        x79 = x78 @ self.c69
        x80 = x79 + 1
        x81 = x71 * x80
        x82 = x27 * x28
        x83 = x82 * x56
        x84 = x82 * x81
        x85 = x84 * -1
        x86 = self.c72 * x29
        x87 = self.c73 * x83
        x88 = x86 + x87
        x89 = self.c74 * x84
        x90 = x88 + x89
        x91 = self.c75 * x29
        x92 = self.c76 * x83
        x93 = x91 - x92
        x94 = self.c77 * x84
        x95 = x93 + x94
        x96 = self.c78 * x30
        x97 = x96 + x87
        x98 = self.c79 * x85
        x99 = x97 + x98
        x100 = self.c80 * x30
        x101 = x100 - x92
        x102 = self.c81 * x85
        x103 = x101 + x102
        x104 = x90 * x90
        x105 = x95 * x95
        x106 = x104 + x105
        x107 = x106 - self.c82
        x108 = x99 * x99
        x109 = x103 * x103
        x110 = x108 + x109
        x111 = x110 - self.c82
        x112 = x18.permute((1, 0))
        x113 = self.c83 @ x112
        x114 = x113.permute((1, 0))
        x115 = x19.permute((1, 0))
        x116 = self.c83 @ x115
        x117 = x116.permute((1, 0))
        x118 = x20.permute((1, 0))
        x119 = self.c84 @ x118
        x120 = x119.permute((1, 0))
        x121 = x21.permute((1, 0))
        x122 = self.c84 @ x121
        x123 = x122.permute((1, 0))
        x124 = x90.permute((1, 0))
        x125 = self.c85 @ x124
        x126 = x125.permute((1, 0))
        x127 = x99.permute((1, 0))
        x128 = self.c86 @ x127
        x129 = x128.permute((1, 0))
        x130 = x95.permute((1, 0))
        x131 = self.c85 @ x130
        x132 = x131.permute((1, 0))
        x133 = x103.permute((1, 0))
        x134 = self.c86 @ x133
        x135 = x134.permute((1, 0))
        x136 = x22 * x22
        x137 = x120 - x114
        x138 = x137 - x129
        x139 = x138 - x126
        x140 = self.c87 * x136
        x141 = x139 - x140
        x142 = x123 - x117
        x143 = x142 - x135
        x144 = x143 - x132
        x145 = self.c88 * x136
        x146 = x144 + x145
        x147 = torch.cat([x17, x90, x99, x95, x103, x107, x111, x141, x146], dim=1)
        return x147
